name: Malcolm X
description: The future belongs to those who prepare for it today.
baseurl: ''
lang: en

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title

# Includes / Excludes
include: ['.htaccess']
exclude: ['node_modules', 'bower_components', 'Gulpfile.js', 'packages.json', 'bower.json', '.bowerrc', '.editorconfig']
